# Config file for automatic testing at travis-ci.org
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  
before_install:
  - openssl aes-256-cbc -K $encrypted_cf94abc85bdc_key -iv $encrypted_cf94abc85bdc_iv -in .env.enc -out .env -d

install: "pip install -r requirements.txt"

script:
  - python test.py
  
after_success:
  - codecov
