# Config file for automatic testing at travis-ci.org
os: osx

osx_image: xcode12.2

language: python

install: "pip install -r requirements.txt"

script:
  - python test.py
  
after_success:
  - codecov
