# Config file for automatic testing at travis-ci.org
os: osx

osx_image: xcode12.2

language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

install: "pip install -r requirements.txt"

script:
  - python test.py
  
after_success:
  - codecov
